// Generated by scripts/optimize-equipment-images.mjs.
export type EquipmentImage = { alt: string; width: number; height: number; src: string; avifSrc: string; avifSrcSet: string; webpSrcSet: string };
export const EQUIPMENT_IMAGES: Record<string, EquipmentImage> = {
  "dry-van": {
    "alt": "Red semi tractor with a white enclosed dry van trailer at a freight terminal",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/dry-van-1200-v1.webp",
    "avifSrc": "/images/equipment/dry-van-1200-v1.avif",
    "avifSrcSet": "/images/equipment/dry-van-480-v1.avif 480w, /images/equipment/dry-van-768-v1.avif 768w, /images/equipment/dry-van-1200-v1.avif 1200w, /images/equipment/dry-van-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/dry-van-480-v1.webp 480w, /images/equipment/dry-van-768-v1.webp 768w, /images/equipment/dry-van-1200-v1.webp 1200w, /images/equipment/dry-van-1536-v1.webp 1536w"
  },
  "reefer": {
    "alt": "Red semi tractor with a white refrigerated trailer and front-mounted refrigeration unit",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/reefer-1200-v1.webp",
    "avifSrc": "/images/equipment/reefer-1200-v1.avif",
    "avifSrcSet": "/images/equipment/reefer-480-v1.avif 480w, /images/equipment/reefer-768-v1.avif 768w, /images/equipment/reefer-1200-v1.avif 1200w, /images/equipment/reefer-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/reefer-480-v1.webp 480w, /images/equipment/reefer-768-v1.webp 768w, /images/equipment/reefer-1200-v1.webp 1200w, /images/equipment/reefer-1536-v1.webp 1536w"
  },
  "flatbed": {
    "alt": "Red semi tractor with an empty single-level flatbed trailer",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/flatbed-1200-v1.webp",
    "avifSrc": "/images/equipment/flatbed-1200-v1.avif",
    "avifSrcSet": "/images/equipment/flatbed-480-v1.avif 480w, /images/equipment/flatbed-768-v1.avif 768w, /images/equipment/flatbed-1200-v1.avif 1200w, /images/equipment/flatbed-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/flatbed-480-v1.webp 480w, /images/equipment/flatbed-768-v1.webp 768w, /images/equipment/flatbed-1200-v1.webp 1200w, /images/equipment/flatbed-1536-v1.webp 1536w"
  },
  "box-truck": {
    "alt": "Red straight box truck with a white enclosed cargo body at a warehouse",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/box-truck-1200-v1.webp",
    "avifSrc": "/images/equipment/box-truck-1200-v1.avif",
    "avifSrcSet": "/images/equipment/box-truck-480-v1.avif 480w, /images/equipment/box-truck-768-v1.avif 768w, /images/equipment/box-truck-1200-v1.avif 1200w, /images/equipment/box-truck-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/box-truck-480-v1.webp 480w, /images/equipment/box-truck-768-v1.webp 768w, /images/equipment/box-truck-1200-v1.webp 1200w, /images/equipment/box-truck-1536-v1.webp 1536w"
  },
  "power-only": {
    "alt": "Red sleeper-cab semi tractor with an exposed fifth wheel and no trailer attached",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/power-only-1200-v1.webp",
    "avifSrc": "/images/equipment/power-only-1200-v1.avif",
    "avifSrcSet": "/images/equipment/power-only-480-v1.avif 480w, /images/equipment/power-only-768-v1.avif 768w, /images/equipment/power-only-1200-v1.avif 1200w, /images/equipment/power-only-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/power-only-480-v1.webp 480w, /images/equipment/power-only-768-v1.webp 768w, /images/equipment/power-only-1200-v1.webp 1200w, /images/equipment/power-only-1536-v1.webp 1536w"
  },
  "step-deck": {
    "alt": "Red semi tractor with an empty step deck trailer showing its raised front and lower main deck",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/step-deck-1200-v1.webp",
    "avifSrc": "/images/equipment/step-deck-1200-v1.avif",
    "avifSrcSet": "/images/equipment/step-deck-480-v1.avif 480w, /images/equipment/step-deck-768-v1.avif 768w, /images/equipment/step-deck-1200-v1.avif 1200w, /images/equipment/step-deck-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/step-deck-480-v1.webp 480w, /images/equipment/step-deck-768-v1.webp 768w, /images/equipment/step-deck-1200-v1.webp 1200w, /images/equipment/step-deck-1536-v1.webp 1536w"
  },
  "hotshot": {
    "alt": "Red heavy-duty pickup towing a gooseneck flatbed hotshot trailer",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/hotshot-1200-v1.webp",
    "avifSrc": "/images/equipment/hotshot-1200-v1.avif",
    "avifSrcSet": "/images/equipment/hotshot-480-v1.avif 480w, /images/equipment/hotshot-768-v1.avif 768w, /images/equipment/hotshot-1200-v1.avif 1200w, /images/equipment/hotshot-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/hotshot-480-v1.webp 480w, /images/equipment/hotshot-768-v1.webp 768w, /images/equipment/hotshot-1200-v1.webp 1200w, /images/equipment/hotshot-1536-v1.webp 1536w"
  },
  "cargo-van": {
    "alt": "Red standard-roof cargo van with enclosed side panels at a loading warehouse",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/cargo-van-1200-v1.webp",
    "avifSrc": "/images/equipment/cargo-van-1200-v1.avif",
    "avifSrcSet": "/images/equipment/cargo-van-480-v1.avif 480w, /images/equipment/cargo-van-768-v1.avif 768w, /images/equipment/cargo-van-1200-v1.avif 1200w, /images/equipment/cargo-van-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/cargo-van-480-v1.webp 480w, /images/equipment/cargo-van-768-v1.webp 768w, /images/equipment/cargo-van-1200-v1.webp 1200w, /images/equipment/cargo-van-1536-v1.webp 1536w"
  },
  "sprinter-van": {
    "alt": "Red high-roof long-wheelbase Sprinter-style cargo van at a freight facility",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/sprinter-van-1200-v1.webp",
    "avifSrc": "/images/equipment/sprinter-van-1200-v1.avif",
    "avifSrcSet": "/images/equipment/sprinter-van-480-v1.avif 480w, /images/equipment/sprinter-van-768-v1.avif 768w, /images/equipment/sprinter-van-1200-v1.avif 1200w, /images/equipment/sprinter-van-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/sprinter-van-480-v1.webp 480w, /images/equipment/sprinter-van-768-v1.webp 768w, /images/equipment/sprinter-van-1200-v1.webp 1200w, /images/equipment/sprinter-van-1536-v1.webp 1536w"
  },
  "conestoga": {
    "alt": "Red semi tractor with a rolling-tarp Conestoga flatbed trailer",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/conestoga-1200-v1.webp",
    "avifSrc": "/images/equipment/conestoga-1200-v1.avif",
    "avifSrcSet": "/images/equipment/conestoga-480-v1.avif 480w, /images/equipment/conestoga-768-v1.avif 768w, /images/equipment/conestoga-1200-v1.avif 1200w, /images/equipment/conestoga-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/conestoga-480-v1.webp 480w, /images/equipment/conestoga-768-v1.webp 768w, /images/equipment/conestoga-1200-v1.webp 1200w, /images/equipment/conestoga-1536-v1.webp 1536w"
  },
  "rgn-lowboy": {
    "alt": "Red heavy-haul tractor with a detachable-gooseneck lowboy trailer and low center deck",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/rgn-lowboy-1200-v1.webp",
    "avifSrc": "/images/equipment/rgn-lowboy-1200-v1.avif",
    "avifSrcSet": "/images/equipment/rgn-lowboy-480-v1.avif 480w, /images/equipment/rgn-lowboy-768-v1.avif 768w, /images/equipment/rgn-lowboy-1200-v1.avif 1200w, /images/equipment/rgn-lowboy-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/rgn-lowboy-480-v1.webp 480w, /images/equipment/rgn-lowboy-768-v1.webp 768w, /images/equipment/rgn-lowboy-1200-v1.webp 1200w, /images/equipment/rgn-lowboy-1536-v1.webp 1536w"
  },
  "car-hauler": {
    "alt": "Red semi tractor with an open two-level car-hauler trailer carrying passenger vehicles",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/car-hauler-1200-v1.webp",
    "avifSrc": "/images/equipment/car-hauler-1200-v1.avif",
    "avifSrcSet": "/images/equipment/car-hauler-480-v1.avif 480w, /images/equipment/car-hauler-768-v1.avif 768w, /images/equipment/car-hauler-1200-v1.avif 1200w, /images/equipment/car-hauler-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/car-hauler-480-v1.webp 480w, /images/equipment/car-hauler-768-v1.webp 768w, /images/equipment/car-hauler-1200-v1.webp 1200w, /images/equipment/car-hauler-1536-v1.webp 1536w"
  },
  "tanker": {
    "alt": "Red semi tractor with a cylindrical stainless-steel tanker trailer",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/tanker-1200-v1.webp",
    "avifSrc": "/images/equipment/tanker-1200-v1.avif",
    "avifSrcSet": "/images/equipment/tanker-480-v1.avif 480w, /images/equipment/tanker-768-v1.avif 768w, /images/equipment/tanker-1200-v1.avif 1200w, /images/equipment/tanker-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/tanker-480-v1.webp 480w, /images/equipment/tanker-768-v1.webp 768w, /images/equipment/tanker-1200-v1.webp 1200w, /images/equipment/tanker-1536-v1.webp 1536w"
  },
  "dump-truck": {
    "alt": "Red four-axle dump truck with its open-top steel body lowered at an aggregate yard",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/dump-truck-1200-v1.webp",
    "avifSrc": "/images/equipment/dump-truck-1200-v1.avif",
    "avifSrcSet": "/images/equipment/dump-truck-480-v1.avif 480w, /images/equipment/dump-truck-768-v1.avif 768w, /images/equipment/dump-truck-1200-v1.avif 1200w, /images/equipment/dump-truck-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/dump-truck-480-v1.webp 480w, /images/equipment/dump-truck-768-v1.webp 768w, /images/equipment/dump-truck-1200-v1.webp 1200w, /images/equipment/dump-truck-1536-v1.webp 1536w"
  },
  "curtain-side": {
    "alt": "Red semi tractor with a curtain-side trailer showing its fixed roof and sliding side curtain",
    "width": 1200,
    "height": 800,
    "src": "/images/equipment/curtain-side-1200-v1.webp",
    "avifSrc": "/images/equipment/curtain-side-1200-v1.avif",
    "avifSrcSet": "/images/equipment/curtain-side-480-v1.avif 480w, /images/equipment/curtain-side-768-v1.avif 768w, /images/equipment/curtain-side-1200-v1.avif 1200w, /images/equipment/curtain-side-1536-v1.avif 1536w",
    "webpSrcSet": "/images/equipment/curtain-side-480-v1.webp 480w, /images/equipment/curtain-side-768-v1.webp 768w, /images/equipment/curtain-side-1200-v1.webp 1200w, /images/equipment/curtain-side-1536-v1.webp 1536w"
  }
};
