// Generated by scripts/optimize-static-photos.mjs. Do not edit by hand.
export const STATIC_PHOTOS = {
  "/video/hero-highway.jpg": {
    "width": 1920,
    "height": 1080,
    "src": "/images/photos/hero-highway-1200-v1.webp",
    "avifSrc": "/images/photos/hero-highway-1200-v1.avif",
    "webpSrcSet": "/images/photos/hero-highway-480-v1.webp 480w, /images/photos/hero-highway-768-v1.webp 768w, /images/photos/hero-highway-1200-v1.webp 1200w, /images/photos/hero-highway-1600-v1.webp 1600w, /images/photos/hero-highway-1920-v1.webp 1920w",
    "avifSrcSet": "/images/photos/hero-highway-480-v1.avif 480w, /images/photos/hero-highway-768-v1.avif 768w, /images/photos/hero-highway-1200-v1.avif 1200w, /images/photos/hero-highway-1600-v1.avif 1600w, /images/photos/hero-highway-1920-v1.avif 1920w"
  },
  "/video/cta-highway.jpg": {
    "width": 1600,
    "height": 900,
    "src": "/images/photos/cta-highway-1200-v1.webp",
    "avifSrc": "/images/photos/cta-highway-1200-v1.avif",
    "webpSrcSet": "/images/photos/cta-highway-480-v1.webp 480w, /images/photos/cta-highway-768-v1.webp 768w, /images/photos/cta-highway-1200-v1.webp 1200w, /images/photos/cta-highway-1600-v1.webp 1600w",
    "avifSrcSet": "/images/photos/cta-highway-480-v1.avif 480w, /images/photos/cta-highway-768-v1.avif 768w, /images/photos/cta-highway-1200-v1.avif 1200w, /images/photos/cta-highway-1600-v1.avif 1600w"
  }
} as const;

export type StaticPhotoSource = keyof typeof STATIC_PHOTOS;
